apiVersion: 1

deleteDatasources:
  - name: Tempo
    orgId: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    isDefault: false
    editable: false
